# Load sheldon-managed plugins. Source the pre-rendered output (generated by
# home.activation.precomputeShellInit) to avoid the subprocess. Falls back
# to live `sheldon source` if the cache is missing. Must run before any code
# that uses zsh-defer (e.g. deferred.zsh) since sheldon defines zsh-defer.
if [[ -f "${XDG_CACHE_HOME:-$HOME/.cache}/sheldon/source.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/sheldon/source.zsh"
else
    eval "$(sheldon source)"
fi
