format = """
[](#9A348E)\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$golang\
$nodejs\
$rust\
[](fg:#86BBD8 bg:#06969A)\
$memory_usage\
[](fg:#06969A bg:#33658A)\
$time\
[](fg:#33658A)\
$line_break\
$character\
"""

[username]
style_root = "bg:#9A348E"
style_user = "bg:#9A348E"
format = '[$user ]($style)'
show_always = true
disabled = false

[directory]
truncate_to_repo = false
format = '[ $path ]($style)'
style = "bg:#DA627D"
truncation_symbol = "…/"

[git_branch]
format = '[ $symbol $branch ]($style)'
symbol = ""
style = "bg:#FCA17D"

[git_status]
format = '[$all_status$ahead_behind ]($style)'
style = "bg:#FCA17D"

[golang]
format = '[ $symbol ($version) ]($style)'
symbol = ""
style = "bg:#86BBD8"

[nodejs]
format = '[ $symbol ($version) ]($style)'
symbol = ""
style = "bg:#86BBD8"

[rust]
format = '[ $symbol ($version) ]($style)'
symbol = ""
style = "bg:#86BBD8"

[memory_usage]
threshold = 0
format = '[ $symbol$ram ]($style)'
style = "bg:#06969A"
disabled = false

[time]
format = '[ $time ]($style)'
time_format = "%T"
style = "bg:#33658A"
disabled = false
